language: python
sudo: false

matrix:
  include:
    - env: CONFIGURATION=API
      python: "3.4"
    - env: CONFIGURATION=WEBSITE
      python: "3.4"
    - env: CONFIGURATION=PRODUCTION
      python: "3.4"

install:
  - pip install coveralls

script:
  - export CONFIGURATION; ./travis_test.sh

after_success: coveralls
