language: python

matrix:
  include:
    - env: CONFIGURATION=API
      python: "3.4"
    - env: CONFIGURATION=WEBSITE
      python: "3.4"
    - env: CONFIGURATION=PRODUCTION
      python: "3.4"

script:
  - export CONFIGURATION; ./travis_test.sh
