language: python
python:
  - "3.4"

install:
  - pip install -r api_requirements.txt

script:
  - python -m contracts.tools.example
  - PYTHONPATH=$PYTHONPATH:`pwd` django-admin.py test --settings=law.tests.settings law.tests
